Fix summary for 1 value variables (python 3)
In python 3, running pm.summary on one value variables (1d traces) give
an error (line 123 of trace.py):

  TypeError: type numpy.ndarray doesn't define __round__ method

Running this code on python 2 versus 3 will reproduce the error (numpy
1.9.0.dev-74e5c12).

  import numpy as np

  x = np.arange(4)

  index = None
  mean = x.mean(0)
  print(round(mean[index], 3))

To avoid this, I have changed the code to use the following method for
1d traces.

  import numpy as np
  x = np.arange(4)

  index = 0
  x = x[:, None]

  mean = x.mean(0)
  print(round(mean[index], 3))

The commit also moves stats calculations outside the trace index loop to
avoid unnecessarily repeating them.